spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD} # Use an App Password, not your real password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
  notification:
    sender:
      mail: ${MAIL_USERNAME} # Best practice: match your auth email
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    # Tells Flyway to look into every module's resources for scripts
#    locations:
#      - classpath:db/migration/identity
#      - classpath:db/migration/task
#      - classpath:db/migration/activity
#      - classpath:db/migration/admin